### ISSUE TITLE
Input network line data is expected to be in a meter-based projection

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/neatnet#142]
Something I have completely overlooked in the docs is that the input network line data is expected to be in a meter-based projection (correct me if for some reason I am wrong).

* We need to be be clear about this – perhaps in a `NOTES` section of `simplify_network()`
* Add appropriate language in any/all docstrings for numeric parameters based on distance/area

**Comment by martinfleis** [comment]
It has to be projected. The defaults assume meters but if you adapt defaults, you could likely work with feet for example.
