### ISSUE TITLE
add ci_artifacts to gitignore

### ISSUE THREAD

**Issue by martinfleis** [uscuni/neatnet#145]
@jGaboardi shall we add the `ci_artifacts` folder to gitignore? When running tests locally, it is created and git sees the files. Or is it going to break that upload action?

**Comment by jGaboardi** [comment]
Let's add it do `gitignore` and remove [`ci_artifacts`](https://github.com/uscuni/neatnet/commits/main/ci_artifacts) (seems we accidentally added that yesterday.

That shouldn't break the upload action, but if it does we can figure out a better solution.
