### ISSUE TITLE
test do not run from installed package

### ISSUE THREAD

**Issue by martinfleis** [uscuni/neatnet#156]
Given we depend on our data files that are not shipped with the package (and should not), the tests currently do not run when you try to run them from the installed package via `pytest --pyargs neatnet`. See https://github.com/pysal/libpysal/actions/runs/12287585100/job/34289870890

We can either:

- ignore it and skip neatnet in libpysal reverse dep testing
- somehow skip tests that require local files by default and enable them on demand (in our CI)
- use something like `pooch` to deal with the file download if it is requested by tests

given that geopandas currently does not run either when tests are invoked in this way, I am not sure how big of a problem it is. We do test against bleeding libpysal here so that is covered, so maybe the option one is the optimal one.

@jGaboardi thoughts?

**Comment by jGaboardi** [comment]
Since bullet requires absolutely nothing from "our" end let's do that? For the the `libpysal` end, is that simply adding adding some logic the reverse dep testing yaml?

**Comment by martinfleis** [comment]
fixing on libpysal CI side

**Comment by jGaboardi** [comment]
xref https://github.com/pysal/libpysal/pull/771
