### ISSUE TITLE
keeping attributes

### ISSUE THREAD

**Issue by jGaboardi** [uscuni/neatnet#6]
* network edge attribution piped through simplification process to final product

**Comment by jGaboardi** [comment]
@anastassiavybornova @martinfleis 

Do yall have an idea in which function(s) this will/should be happening?

**Comment by martinfleis** [comment]
Primarily where we change the overall geometry of the dataframe. I am not fully sure without checking where we drop the data but the information on status is carried through so the rest should be feasible as well.

**Comment by jGaboardi** [comment]
Resolved via #132

**Comment by gsagostini** [comment]
Hi! Does this issue refer to ways of keeping track of edge attributes throughout the `neatify` function? Is there a currently implemented way one can track original indices or attributes to edges after a neatify loop?

I noticed that while the edge attributes for the original edges are always present, attributes for `changed` or even `new` edges are sometimes present and sometimes not. The documentation just says "the attributes from the original network are preserved, but keep in mind that they may no longer be valid for changed geometries" (on the user guide adaptive example). Even if there is no current work around to maintain edge index information, is there a way to know whether to trust the attributes that were maintained? I also don't understand why an edge whose status is `new` could inherit an attribute.

(let me know if this is a different issue, happy to provide more context/examples too!)

**Comment by martinfleis** [comment]
I guess we may need to look into that a bit. Regarding the trust, the note refers to the value. You may have a column representing length, which if preserved is no longer valid if the lien is changed along the way. While a street name would be fine. 

New lines should not have anything. If they do, that can be considered a bug.

**Comment by gsagostini** [comment]
Ok then I think I found a bug. Some lines labeled new are receiving attributes in my case. Will try to create a reproducible example, thanks!
