### ISSUE TITLE
brainstorm package name

### ISSUE THREAD

**Issue by anastassiavybornova** [uscuni/neatnet#64]
must haves:
* not on pypi.org
* not on prefix.dev
* not on conda-forge
* searchable on the internet
* looks pronounceable

**Comment by jGaboardi** [comment]
<img width="25" alt="Screenshot 2024-10-24 at 10 29 56 AM" src="https://github.com/user-attachments/assets/60b399c7-4048-4b38-a40b-c45b6db995e2">

**Comment by anastassiavybornova** [comment]
suggestions from michael:
* blockbuster
* streetcleaner

**Comment by martinfleis** [comment]
Does it actually fullfils _searchable on the internet_?

Keep in mind that it should also contain all the other preprocessing tools from momepy.

**Comment by anastassiavybornova** [comment]
@martinfleis  no it doesn't, but still adding it here for future brainstorming inspiration

**Comment by jGaboardi** [comment]
"Metzger: The Street Butcher"

**Comment by anastassiavybornova** [comment]
"street_stitcher"

(was thinking of a less bloody equivalent of butchering, and actually what happens is the opposite of butchering - as in putting stuff (back) together?)

@jGaboardi what are other handcraft activites along stitching/sewing/... lines?

**Comment by jGaboardi** [comment]
>  less bloody equivalent

🤣

**Comment by jGaboardi** [comment]
> handcraft activites along stitching/sewing/...
* seam
* tailor
* darn

**Comment by jGaboardi** [comment]
Also something like "uncluttered"

**Comment by martinfleis** [comment]
These _normal words_ are pain to google.

I'd also like to avoid underscores.

**Comment by jGaboardi** [comment]
`streetneat`

**Comment by martinfleis** [comment]
`neatstreet`

**Comment by jGaboardi** [comment]
Both `streetneat` & `neatstreet` meet [all conditions above](https://github.com/uscuni/sgeop/issues/64#issue-2611704620).

**Comment by martinfleis** [comment]
`neatnet`

**Comment by jGaboardi** [comment]
`cleannet`

**Comment by jGaboardi** [comment]
`cleanstreets`

**Comment by jGaboardi** [comment]
`meanstreets` ≈("average/uncluttered/de-complexified" streets network geometry)

**Comment by jGaboardi** [comment]
`tidyway`

**Comment by jGaboardi** [comment]
`streetsorter`

**Comment by jGaboardi** [comment]
`streettriage`

**Comment by anastassiavybornova** [comment]
`neatstreet` <3 <3 <3 

`neatnet` also <3 <3 

yay i think we're getting there!!

**Comment by jGaboardi** [comment]
We decided on `neatnet` during meeting [2024-12-2]

**Comment by jGaboardi** [comment]
@martinfleis & @anastassiavybornova 

Once we get a tag + release out we can close this 🎉

**Comment by jGaboardi** [comment]
Now released on PyPI --> https://pypi.org/project/neatnet/0.0.1/
